#!/bin/bash
projname=$(sed -n 1p lumake)
server=$(sed -n 2p lumake)
init=$(sed -n 3p lumake)
run=$(sed -n 4p lumake)
build=$(sed -n 5p lumake)
version=$(sed -n 6p lumake)




if [[ $1 == "commit" ]]; then
   read pass
   zip -r main.zip ./*
   curl -F 'data=@main.zip' "$server?func=commit&name=$projname&password=$pass"
   rm main.zip
fi

if [[ $1 == "get" ]]; then
   read pass
   curl -o main.zip "$server?func=get&name=$projname&password=$pass"   
   unzip -o main.zip
   rm main.zip
fi




if [[ $1 == "init" ]]; then
$init ${@:2}
fi
if [[ $1 == "run" ]]; then
$run ${@:2}
fi
if [[ $1 == "build" ]]; then
$build ${@:2}
fi



if [[ $1 == "server" ]]; then
    read pass
    if [[ $3 == "clone" ]]; then

	    
        curl -o main.zip "$2?func=clone&name=$4&password=$pass"   
        unzip -o main.zip
        rm main.zip
	fi
	if [[ $3 == "remove" ]]; then

        curl "$2?func=remove&name=$4&password=$pass"
		


	fi
	if [[ $3 == "init" ]]; then


		curl "$2?func=init&name=$4&password=$pass" 
		

	fi
	if [[ $3 == "run" ]]; then


		curl "$2?func=run&name=$4&password=$pass" &
		

	fi
	if [[ $3 == "build" ]]; then


		curl "$2?func=build&name=$4&password=$pass" &

	fi
	if [[ $3 == "version" ]]; then


		curl "$2?func=version&name=$4&password=$pass"
		

	fi
fi
